# Generated by Django 5.2 on 2025-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('A', 'Level A'), ('B', 'Level B'), ('C', 'Level C'), ('D', 'Level D')], max_length=1)),
                ('tags', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
    ]
